Moonofweisheng/wot-design-uni

.gitignore
docs/.vitepress/config.ts
docs/component/notify.md
src/components/page-wraper/page-wraper.vue
src/pages.json
src/pages/index/Index.vue
src/pages/notify/Index.vue
src/uni_modules/wot-design-uni/components/common/abstracts/variable.scss
src/uni_modules/wot-design-uni/components/common/util.ts
src/uni_modules/wot-design-uni/components/wd-notify/index.scss
src/uni_modules/wot-design-uni/components/wd-notify/index.ts
src/uni_modules/wot-design-uni/components/wd-notify/type.ts
src/uni_modules/wot-design-uni/components/wd-notify/wd-notify.vue
src/uni_modules/wot-design-uni/index.ts

* feat: ✨ 新增Notify组件、演示demo、文档
* feat: ✨ 新增Notify组件、演示demo、文档

feat: ✨ 新增Notify组件、演示demo、文档 (#9)

---

src/components/page-wraper/page-wraper.vue
src/pages/notify/Index.vue
src/uni_modules/wot-design-uni/components/wd-action-sheet/wd-action-sheet.vue
src/uni_modules/wot-design-uni/components/wd-calendar-view/monthPanel/month-panel.vue
src/uni_modules/wot-design-uni/components/wd-calendar-view/yearPanel/year-panel.vue
src/uni_modules/wot-design-uni/components/wd-calendar/wd-calendar.vue
src/uni_modules/wot-design-uni/components/wd-collapse/wd-collapse.vue
src/uni_modules/wot-design-uni/components/wd-datetime-picker-view/wd-datetime-picker-view.vue
src/uni_modules/wot-design-uni/components/wd-datetime-picker/index.scss
src/uni_modules/wot-design-uni/components/wd-datetime-picker/wd-datetime-picker.vue
src/uni_modules/wot-design-uni/components/wd-drop-menu-item/wd-drop-menu-item.vue
src/uni_modules/wot-design-uni/components/wd-drop-menu/wd-drop-menu.vue
src/uni_modules/wot-design-uni/components/wd-loading/wd-loading.vue
src/uni_modules/wot-design-uni/components/wd-message-box/index.ts
src/uni_modules/wot-design-uni/components/wd-message-box/wd-message-box.vue
src/uni_modules/wot-design-uni/components/wd-notify/index.ts
src/uni_modules/wot-design-uni/components/wd-notify/wd-notify.vue
src/uni_modules/wot-design-uni/components/wd-picker-view/wd-picker-view.vue
src/uni_modules/wot-design-uni/components/wd-picker/index.scss
src/uni_modules/wot-design-uni/components/wd-picker/wd-picker.vue
src/uni_modules/wot-design-uni/components/wd-popup/type.ts
src/uni_modules/wot-design-uni/components/wd-popup/wd-popup.vue
src/uni_modules/wot-design-uni/components/wd-toast/index.ts
src/uni_modules/wot-design-uni/components/wd-toast/type.ts
src/uni_modules/wot-design-uni/components/wd-toast/wd-toast.vue

[fix: 🐛 修复pmpm安装时ts导入类型信息在H5平台报错的问题](https://github.com/Moonofweisheng/wot-design-uni/commit/3dff95af8276a5318b1c1387bf87a1e90c3fef44)  
[fix: 🐛 修复ActionSheet等组件在H5端隐藏导航栏或在tabbar页面高度计算错误的问题](https://github.com/Moonofweisheng/wot-design-uni/commit/aee71b31d0068ecf696ff84ab57bfadd7ff51a42)

fix: 🐛 修复pmpm安装时ts导入类型信息在H5平台报错的问题

---

docs/component/tabs.md
src/pages/tabs/Index.vue
src/uni_modules/wot-design-uni/components/wd-popover/wd-popover.vue
src/uni_modules/wot-design-uni/components/wd-tab/index.scss
src/uni_modules/wot-design-uni/components/wd-tabs/index.scss
src/uni_modules/wot-design-uni/components/wd-tabs/wd-tabs.vue

fix: 🐛 修复Popover组件content属性必填警告的问题  
feat: ✨ Tabs组件增加animated属性支持切换动画

feat: ✨ Tabs组件增加animated属性支持切换动画

---

docs/.vitepress/config.ts
docs/component/circle.md
docs/component/watermark.md
src/pages.json
src/pages/circle/index.vue
src/pages/grid/Index.vue
src/pages/index/Index.vue
src/uni_modules/wot-design-uni/components/common/abstracts/variable.scss
src/uni_modules/wot-design-uni/components/common/util.ts
src/uni_modules/wot-design-uni/components/wd-cell/wd-cell.vue
src/uni_modules/wot-design-uni/components/wd-circle/index.scss
src/uni_modules/wot-design-uni/components/wd-circle/wd-circle.vue
src/uni_modules/wot-design-uni/components/wd-grid-item/wd-grid-item.vue
src/uni_modules/wot-design-uni/components/wd-notify/index.scss
src/uni_modules/wot-design-uni/components/wd-skeleton/index.scss
src/uni_modules/wot-design-uni/global.d.ts
src/uni_modules/wot-design-uni/readme.md

feat: ✨ 新增 Circle 环形进度条组件，支持进度渐变动画  
fix: 🐛 修复 Cell、Grid 组件跳转方法在编译到H5端失效的问题(https://github.com/Moonofweisheng/wot-design-uni/issues/49)

feat: ✨ 新增 Circle 环形进度条组件，支持进度渐变动画

---

src/pages/circle/Index.vue
src/uni_modules/wot-design-uni/components/wd-circle/wd-circle.vue
src/uni_modules/wot-design-uni/components/wd-skeleton/wd-skeleton.vue
src/uni_modules/wot-design-uni/components/wd-tag/index.scss
src/uni_modules/wot-design-uni/components/wd-tag/wd-tag.vue

fix: 🐛 修复 Skeleton 骨架屏组件编译到APP端异常的问题(https://github.com/Moonofweisheng/wot-design-uni/issues/52)  
fix: 🐛 修复 Circle 组件重复创建canvas导致警告的问题  
fix: 🐛 修复 Tag 组件编译到微信小程序平台样式错误的问题(https://github.com/Moonofweisheng/wot-design-uni/issues/53)

fix: 🐛 修复 Skeleton 骨架屏组件编译到APP端异常的问题(#52)

---

src/uni_modules/wot-design-uni/components/wd-action-sheet/wd-action-sheet.vue
src/uni_modules/wot-design-uni/components/wd-curtain/wd-curtain.vue
src/uni_modules/wot-design-uni/components/wd-drop-menu-item/wd-drop-menu-item.vue
src/uni_modules/wot-design-uni/components/wd-message-box/wd-message-box.vue

在使用其他组件时发现控制台报警告：@clickmodal，查看源码后修复

解决wd-popup的emit控制台警告@clickmodal,

---

src/pages/tabs/Index.vue
src/uni_modules/wot-design-uni/components/wd-tabs/wd-tabs.vue

feat: ✨ Tabs 组件调整为受控组件

---

docs/component/navbar.md
docs/component/select-picker.md
src/uni_modules/wot-design-uni/components/common/util.ts
src/uni_modules/wot-design-uni/components/wd-select-picker/index.scss
src/uni_modules/wot-design-uni/components/wd-select-picker/wd-select-picker.vue

feat: ✨ SelectPicker 单复选选择器增加 scroll-into-view 属性支持定位到选中值

---

docs/component/tabs.md
src/pages/tabs/Index.vue
src/uni_modules/wot-design-uni/components/wd-tabs/wd-tabs.vue

fix: 🐛 修复 Tabs 组件通过name匹配时抛出异常的问题

---

src/pages/tabs/Index.vue
src/uni_modules/wot-design-uni/components/wd-tab/wd-tab.vue
src/uni_modules/wot-design-uni/components/wd-tabs/wd-tabs.vue

fix: 🐛 修复 Tabs 指定name时双向绑定值仍为index的问题

---

src/uni_modules/wot-design-uni/components/wd-collapse-item/index.scss
src/uni_modules/wot-design-uni/components/wd-collapse-item/wd-collapse-item.vue
src/uni_modules/wot-design-uni/components/wd-datetime-picker/wd-datetime-picker.vue

[fix: 🐛 修复 DateTimePicker 日期选择器组件双向绑定错误的问题](https://github.com/Moonofweisheng/wot-design-uni/commit/2915c68688f253c6fa0a26bc7056ac0e524bc249)
[feat: ✨ Collpase 折叠面板组件增加分割线](https://github.com/Moonofweisheng/wot-design-uni/commit/f89f389db736356e7f023c9695302fa82a690513) 
✅ Closes: https://github.com/Moonofweisheng/wot-design-uni/issues/97

feat: ✨ Collpase 折叠面板组件增加分割线 

---

src/uni_modules/wot-design-uni/components/wd-popover/index.scss
src/uni_modules/wot-design-uni/components/wd-popover/wd-popover.vue
src/uni_modules/wot-design-uni/components/wd-tooltip/index.scss
src/uni_modules/wot-design-uni/components/wd-tooltip/wd-tooltip.vue

fix: 🐛 修复 Popover、Tooltip 组件展开切换动画不流畅的问题

---

src/uni_modules/wot-design-uni/components/wd-datetime-picker/wd-datetime-picker.vue

1.日期范围选择 beforeConfirm  value字段只有单个值问题
2.日期选择title prop增加对象类型/普通数据类型判断

perf: 1.日期选择beforeConfirm增加范围传值 2. title普通字符串出现冒号

---

docs/component/tag.md
src/uni_modules/wot-design-uni/components/wd-tag/wd-tag.vue

feat: Tag新增类型标签添加slot

---

src/uni_modules/wot-design-uni/components/wd-input/index.scss
src/uni_modules/wot-design-uni/components/wd-input/wd-input.vue

feat: Input在readonly状态下可展示placeholder
feat: Input在readonly状态下可展示suffix

feat: Input在readonly状态下可展示placeholder和suffix

---

src/uni_modules/wot-design-uni/components/wd-watermark/wd-watermark.vue

fix: 删除多余代码

---

src/uni_modules/wot-design-uni/components/wd-button/index.scss

style: 💄 移除按钮默认的圆角样式

---

src/uni_modules/wot-design-uni/components/wd-checkbox/types.ts

fix: checkbox 切换无效

---

docs/component/img.md
src/pages/img/Index.vue
src/uni_modules/wot-design-uni/components/wd-img/types.ts
src/uni_modules/wot-design-uni/components/wd-img/wd-img.vue

feat: ✨ img组件增加enable-preview属性来支持点击预览功能

---

docs/component/img.md
docs/component/upload.md
src/pages/img/Index.vue
src/pages/upload/Index.vue
src/uni_modules/wot-design-uni/components/wd-img/types.ts
src/uni_modules/wot-design-uni/components/wd-upload/types.ts
src/uni_modules/wot-design-uni/components/wd-upload/wd-upload.vue

feat: ✨ `upload`组件增加`mode`属性传递给预览`image`

---

docs/component/notice-bar.md
src/pages/noticeBar/Index.vue
src/uni_modules/wot-design-uni/components/wd-notice-bar/types.ts
src/uni_modules/wot-design-uni/components/wd-notice-bar/wd-notice-bar.vue

✅ Closes: #122
#122
1. `notice-bar`组件缺少垂直滚动能力
2. 调整动画`trasnlate`方向，并计算高度即可
```javascript
async function verticalAnimate(height: number) {
const translate = -(height / (textArray.value.length + 1)) * (currentIndex.value + 1)
animation.value = initAnimation({
duration: props.speed * 1000,
delay: props.delay * 1000,
translate
})
}
```

feat: ✨ `notice-bar`增加垂直滚动功能

---

docs/component/notice-bar.md
src/pages/noticeBar/Index.vue
src/uni_modules/wot-design-uni/components/wd-notice-bar/wd-notice-bar.vue

feat: ✨ 增强`notice-bar`组件`vertical`模式下插槽的功能

---

docs/component/notice-bar.md
src/components/page-wraper/page-wraper.vue
src/pages/noticeBar/Index.vue
src/uni_modules/wot-design-uni/components/wd-notice-bar/wd-notice-bar.vue

noticebar组件提供垂直滚动后，在支付宝小程序和微信小程序上滚动异常，将滚动逻辑从uni.createAnimation调整为css动画，同时移除垂直滚动的插槽。

fix: 🐛 修复NoticeBar通知栏在小程序端垂直滚动无效的问题

---

docs/component/message-box.md
docs/component/toast.md
src/pages/messageBox/Index.vue
src/pages/toast/Index.vue
src/uni_modules/wot-design-uni/components/wd-message-box/types.ts
src/uni_modules/wot-design-uni/components/wd-message-box/wd-message-box.vue
src/uni_modules/wot-design-uni/components/wd-toast/index.ts
src/uni_modules/wot-design-uni/components/wd-toast/types.ts
src/uni_modules/wot-design-uni/components/wd-toast/wd-toast.vue

feat: ✨ MessageBox支持确认前置处理钩子beforeConfirm

---

docs/component/checkbox.md
src/pages/checkbox/Index.vue
src/uni_modules/wot-design-uni/components/wd-checkbox/types.ts
src/uni_modules/wot-design-uni/components/wd-checkbox/wd-checkbox.vue

feat: ✨ Checkbox 新增toggle方法

---

docs/component/table.md
src/uni_modules/wot-design-uni/components/wd-sidebar-item/wd-sidebar-item.vue
src/uni_modules/wot-design-uni/components/wd-step/wd-step.vue
src/uni_modules/wot-design-uni/components/wd-tab/wd-tab.vue
src/uni_modules/wot-design-uni/components/wd-tabbar-item/wd-tabbar-item.vue
src/uni_modules/wot-design-uni/components/wd-tabbar/wd-tabbar.vue
src/uni_modules/wot-design-uni/components/wd-table-col/wd-table-col.vue
src/uni_modules/wot-design-uni/components/wd-table/wd-table.vue

feat: ✨ TableColumn组件value插槽新增index参数

---

docs/component/slider.md
src/pages/slider/Index.vue
src/uni_modules/wot-design-uni/components/wd-slider/wd-slider.vue

feat: ✨ `Slider`组件`min`值允许负数

---

docs/component/fab.md
src/pages/fab/Index.vue
src/uni_modules/wot-design-uni/components/common/abstracts/variable.scss
src/uni_modules/wot-design-uni/components/common/util.ts
src/uni_modules/wot-design-uni/components/wd-fab/index.scss
src/uni_modules/wot-design-uni/components/wd-fab/types.ts
src/uni_modules/wot-design-uni/components/wd-fab/wd-fab.vue

将`draggable`设置为`true`可拖动`fab`，拖动完成后自动吸边，并且根据吸边位置更改菜单弹出方向

feat: ✨ fab添加draggable属性

---

src/uni_modules/wot-design-uni/components/wd-slider/wd-slider.vue

https://github.com/Moonofweisheng/wot-design-uni/issues/274

fix: 🐛 Slider组件在watch max和min中添加对滑块和进度条的更新操作

---

build/release.js
docs/component/slider.md

纠正`release`脚本处理最低版本号错误导致的问题

---

src/pages/popover/Index.vue
src/uni_modules/wot-design-uni/components/common/abstracts/_mixin.scss
src/uni_modules/wot-design-uni/components/wd-popover/wd-popover.vue

fix: 🐛 修复Popover指定placement后箭头显示异常的问题。

---

src/pages/navbar/Index.vue
src/uni_modules/wot-design-uni/components/wd-navbar/wd-navbar.vue

style: 💄 缩窄`NavBar`组件的`left`区域hover效果

---

docs/component/button.md
src/uni_modules/wot-design-uni/components/wd-button/index.scss

https://github.com/Moonofweisheng/wot-design-uni/issues/304

fix: 修复wd-button在自定义样式下，按下active时的尺寸问题

---

docs/.vitepress/config.mts
docs/component/indexBar.md
src/pages.json
src/pages/index/Index.vue
src/pages/indexBar/Index.vue
src/uni_modules/wot-design-uni/components/common/abstracts/variable.scss
src/uni_modules/wot-design-uni/components/wd-index-anchor/index.scss
src/uni_modules/wot-design-uni/components/wd-index-anchor/type.ts
src/uni_modules/wot-design-uni/components/wd-index-anchor/wd-index-anchor.vue
src/uni_modules/wot-design-uni/components/wd-index-bar/index.scss
src/uni_modules/wot-design-uni/components/wd-index-bar/type.ts
src/uni_modules/wot-design-uni/components/wd-index-bar/wd-index-bar.vue
src/uni_modules/wot-design-uni/global.d.ts

feat: ✨ 添加索引栏组件

---

src/uni_modules/wot-design-uni/components/wd-number-keyboard/index.scss

style: 💄 修复`NumberKeyboard`在系统为暗黑模式时的异常颜色

---

src/uni_modules/wot-design-uni/components/wd-cell/types.ts
src/uni_modules/wot-design-uni/components/wd-cell/wd-cell.vue

1.value为0或者null，之前仅支持string，value转字符串后，0正常显示，null则显示为字符串null，期望0显示，null隐藏
2.boolean类型也能正常使用，但是需要重新设计type

cell组件value值类型增加支持number

---

docs/component/select-picker.md

docs: update select-picker doc

---

docs/component/img-cropper.md
docs/component/loading.md

修复loading组件示例代码中文标点符号、img-cropper组件示例代码标签缺失

---

docs/component/fab.md
src/uni_modules/wot-design-uni/components/wd-fab/types.ts
src/uni_modules/wot-design-uni/components/wd-fab/wd-fab.vue

feat: ✨ fab组件添加gap属性

---

docs/component/select-picker.md
src/uni_modules/wot-design-uni/components/wd-select-picker/wd-select-picker.vue

feat: ✨select-picker组件增加open、close事件

---

docs/component/swiper.md
src/pages/swiper/Index.vue
src/uni_modules/wot-design-uni/components/wd-swiper/wd-swiper.vue

fix: 🐛 修复Swiper在微信端长时间处于后台出现抖动的问题

---

src/uni_modules/wot-design-uni/components/wd-index-bar/wd-index-bar.vue

fix: 🐛 修复IndexBar索引值显示错误的问题

---

docs/.vitepress/config.mts
docs/component/text.md
src/pages.json
src/pages/index/Index.vue
src/pages/text/Index.vue
src/uni_modules/wot-design-uni/components/common/abstracts/variable.scss
src/uni_modules/wot-design-uni/components/wd-text/index.scss
src/uni_modules/wot-design-uni/components/wd-text/types.ts
src/uni_modules/wot-design-uni/components/wd-text/wd-text.vue

feat: 新增Text 文本

---

docs/component/text.md

docs: ✏️ 更正text组件doc的type属性默认值

---

src/pages/form/demo3.vue
src/uni_modules/wot-design-uni/components/wd-radio/index.scss

Reverts Moonofweisheng/wot-design-uni#631

Revert "fix: 🐛 Radio修复在cell里面高度的问题"

---

src/uni_modules/wot-design-uni/components/wd-select-picker/wd-select-picker.vue

fix: 🐛 修复 wd-select-picker 组件单选搜索高亮 class 错误

---

docs/component/col-picker.md

fix: 🐛 修复Picker文档初始选项code错误的问题

---

.gitignore
babel.config.js
jest.config.js
package.json
pnpm-lock.yaml
tests/composables/useTouch.spec.ts
tests/composables/useTranslate.spec.ts
tests/composables/useUpload.spec.ts
tests/setup.js
tsconfig.json

chore: 🚀 添加 jest 用于组件库工具方法和hooks的测试
