Moonofweisheng/wot-design-uni

- src/uni_modules/wot-design-uni/components/wd-col-picker/wd-col-picker.vue
> fix: 修正ColPicker多列选择器v-model类型提示使用Record<string, any>[]实际上的数据是一维数组的问题

- README.md
> fix: 修正README.md 中[贡献指南]链接错误，跳转失败的问题。

- docs/component/button.md
- src/pages/button/Index.vue
- src/uni_modules/wot-design-uni/components/common/abstracts/_mixin.scss
- src/uni_modules/wot-design-uni/components/common/abstracts/variable.scss
- src/uni_modules/wot-design-uni/components/wd-button/index.scss
- src/uni_modules/wot-design-uni/components/wd-button/wd-button.vue
解决button、tabs等组件使用基于主色生成的渐变色作为背景色，此时不支持通过css变量实现主题的定制的问题。
> 支持通过css变量自定义主色来定制主题

- src/uni_modules/wot-design-uni/components/wd-img/index.scss
- src/uni_modules/wot-design-uni/components/wd-img/wd-img.vue
> fix: 🐛 适配微信小程序css样式选择器命名规范（wd-img）

- docs/component/select-picker.md
- src/pages/selectPicker/Index.vue
- src/uni_modules/wot-design-uni/components/wd-select-picker/types.ts
- src/uni_modules/wot-design-uni/components/wd-select-picker/wd-select-picker.vue
> feat: ✨ SelectPicker单选支持确认按钮可隐藏

- docs/component/search.md
- docs/component/swiper.md
- src/pages/swiper/Index.vue
- src/uni_modules/wot-design-uni/components/wd-search/types.ts
- src/uni_modules/wot-design-uni/components/wd-search/wd-search.vue
- src/uni_modules/wot-design-uni/components/wd-swiper/wd-swiper.vue
- [x ] 日常 bug 修复
- [x ] 站点、文档改进
- [x ] TypeScript 定义更新
无
本次修复Search组件的suffix插槽无法使用的问题，且use-suffix-slot属性是多余的，已标记为@deprecated，下一个中版本将移除该属性
- [ x] 文档已补充或无须补充
- [ x] 代码演示已提供或无须提供
- [ x] TypeScript 定义已补充或无须补充
> fix: 🐛 修复search组件suffix插槽无法使用的问题

- docs/component/img.md
- src/pages/img/Index.vue
- src/uni_modules/wot-design-uni/components/wd-img/types.ts
mode有了类型后就不需要再去赋值mode了，直接类型提示+回车
> feat: ✨ img组件的mode属性增加类型`ImageMode`

- src/uni_modules/wot-design-uni/components/wd-step/wd-step.vue
无
step 组件的 description 插槽设置了 v-if=“$slots.description” 但未设置 name，导致不显示。
解决方案：增加 name=“description ” 属性
> fix: 修复 step 的 description 插槽不显示的bug

- src/pages/button/Index.vue
- src/uni_modules/wot-design-uni/components/common/abstracts/variable.scss
- src/uni_modules/wot-design-uni/components/wd-button/index.scss
- src/uni_modules/wot-design-uni/components/wd-button/wd-button.vue
> fix: 🐛 修复Button不同尺寸显示固定尺寸icon样式不协调的问题

- src/pages/upload/Index.vue
- src/uni_modules/wot-design-uni/components/wd-upload/types.ts
- src/uni_modules/wot-design-uni/components/wd-upload/wd-upload.vue
在使用 wd-upload 组件的自定义插槽功能(use-default-slot)时，设置 limit 属性不生效，即上传文件的数量达到 limit 值后依旧显示上传按钮。
解决方案：将 limit 触发隐藏的逻辑提取到父组件，使得自定义插槽和默认内容都可隐藏
```js
const canUploadMoreFiles = computed(() => !props.limit || uploadFiles.value.length < props.limit)
```
```html
<view v-if="canUploadMoreFiles" @click="handleChoose">
<slot v-if="useDefaultSlot"></slot>
<view v-if="!useDefaultSlot" :class="['wd-upload__evoke', disabled ? 'is-disabled' : '', customEvokeClass]">
....默认内容
</view>
</view>
```
wd-upload 组件的自定义插槽外部包裹了一个 view 用于监听点击事件的，但是这个 view 没有定义类名和支持自定义 class 的属性，因此在使用组件的时候没办法完全控制自定义插槽的父元素的宽度和高度等。
解决方案：增加 customEvokeWrapperClass 属性，用于自定义自定义插槽外层元素的类样式
> fix: 修正upload组件使用自定义插槽时上传文件数量达到limit值后不自动隐藏上传按钮的问题，以及增加支持插槽外部容器的样式自定义

- docs/component/datetime-picker-view.md
- docs/component/datetime-picker.md
- src/pages/datetimePicker/Index.vue
- src/pages/datetimePickerView/Index.vue
- src/uni_modules/wot-design-uni/components/wd-datetime-picker-view/types.ts
- src/uni_modules/wot-design-uni/components/wd-datetime-picker-view/wd-datetime-picker-view.vue
- src/uni_modules/wot-design-uni/components/wd-datetime-picker/wd-datetime-picker.vue
> datetime-picker添加年选择器

- src/uni_modules/wot-design-uni/components/wd-input-number/wd-input-number.vue
修改@change逻辑，应该先传值，再触发change，这样新的值可以被@change事件取到
> 修改@change逻辑，应该先传值，再触发change，这样新的值可以被@change事件取到

- src/uni_modules/wot-design-uni/components/wd-input-number/wd-input-number.vue
InputNumber步进器组件在初始化时未发生变化仍触发change事件  
解决方案：控制只有在值发生变化时才触发change
> fix: 🐛 修复InputNumber步进器组件在初始化时未发生变化仍触发change的问题

- docs/component/table.md
- src/pages/table/Index.vue
- src/uni_modules/wot-design-uni/components/wd-table/types.ts
- src/uni_modules/wot-design-uni/components/wd-table/wd-table.vue
- src/uni_modules/wot-design-uni/locale/lang/en-US.ts
- src/uni_modules/wot-design-uni/locale/lang/th-TH.ts
- src/uni_modules/wot-design-uni/locale/lang/vi-VN.ts
- src/uni_modules/wot-design-uni/locale/lang/zh-CN.ts
- src/uni_modules/wot-design-uni/locale/lang/zh-HK.ts
- src/uni_modules/wot-design-uni/locale/lang/zh-TW.ts
resolve #191
通过index设置表格是否显示序号列，默认为false。同时也可以传入对象对序号列进行配置，参数同TableColumnProps
```vue
<wd-table :data="dataList" height="328px" :index="true">
<wd-table-col prop="name" label="姓名" :sortable="true"></wd-table-col>
<wd-table-col prop="grade" label="分数" :sortable="true"></wd-table-col>
<wd-table-col prop="hobby" label="一言以蔽之" :sortable="true" :width="160"></wd-table-col>
</wd-table>
<wd-table :data="dataList" height="328px" :index="{ align: 'center', width: 200 }">
<wd-table-col prop="name" label="姓名" :sortable="true" align="center"></wd-table-col>
<wd-table-col prop="grade" label="分数" :sortable="true" align="center"></wd-table-col>
<wd-table-col prop="hobby" label="一言以蔽之" :sortable="true" :width="160"></wd-table-col>
</wd-table>
```
> feat: ✨ table组件添加index参数

- src/uni_modules/wot-design-uni/components/wd-calendar/types.ts
- src/uni_modules/wot-design-uni/components/wd-calendar/wd-calendar.vue
1. 关闭或者退出页面的时候需要调用api自动关闭当前没有关闭的选择器，经过源码驱动，发现事件没有抛出
解决方案
1. 通过vue的事件正常抛出
> fix: 修复wd-calendar未抛出事件

- docs/component/segmented.md
- src/uni_modules/wot-design-uni/components/wd-segmented/wd-segmented.vue
需求背景：直接更新 value 值也会触发 change 事件，比如通过接口获取值给组件赋值，希望用户切换选项时才出发事件
解决方案：增加 click 事件，用户点击时触发
> feat: segmented组件添加click事件

- docs/component/img.md
- src/pages/img/Index.vue
- src/uni_modules/wot-design-uni/components/wd-img/wd-img.vue
> feat: ✨ img组件添加loading error插槽

- src/uni_modules/wot-design-uni/components/wd-form/wd-form.vue
当prop为多级嵌套结构时，正则或者自定义校验器时，无法获取对应的输入值
- [x ] 日常 bug 修复
- [x ] 文档已补充或无须补充
> fix: 🐛 wd-form针对多级对象校验，校验器无法获取到对应value值bug修复

- src/uni_modules/wot-design-uni/components/wd-sort-button/wd-sort-button.vue
-[x]代码演示已提供或无须提供
-[x]TypeScript 定义已补充或无须补充
> 修正一个小bug，在sort-button的handleClick事件中，应该先更新值，再触发@change事件，这样新的值可以被@change事件取到

- src/pages/tabs/Index.vue
- src/uni_modules/wot-design-uni/components/wd-sticky-box/types.ts
- src/uni_modules/wot-design-uni/components/wd-sticky-box/wd-sticky-box.vue
- src/uni_modules/wot-design-uni/components/wd-sticky/wd-sticky.vue
Sticky组件在h5和App端缓慢拖动时存在几率始终固定在顶部。
> fix: 🐛 修复Sticky在h5和App端缓慢拖动时存在几率始终固定在顶部的问题

- src/pages/circle/Index.vue
- src/uni_modules/wot-design-uni/components/common/canvasHelper.ts
- src/uni_modules/wot-design-uni/components/wd-circle/wd-circle.vue
微信小程序端canvas无法被弹出框遮挡，现在调整为微信端使用type="2d"将canvas指定为canvas2d
> feat: ✨ 调整Circle环形进度条在微信小程序端使用canvas2d支持同层渲染

- src/pages/table/Index.vue
- src/uni_modules/wot-design-uni/components/wd-segmented/wd-segmented.vue
- src/uni_modules/wot-design-uni/components/wd-table-col/types.ts
- src/uni_modules/wot-design-uni/components/wd-table-col/wd-table-col.vue
- src/uni_modules/wot-design-uni/components/wd-table/types.ts
- src/uni_modules/wot-design-uni/components/wd-table/wd-table.vue
- src/uni_modules/wot-design-uni/components/wd-tabs/wd-tabs.vue
> refactor: ♻️ 重构table父子组件的数据交互

- docs/component/upload.md
只是个小错误所以没有提issue
直接复制文档样例来用的人还是挺多的，这包括我在内。
我复制了upload的样例直接使用，发现每次第一次上传图片都不显示，事前添加的图片列表在点上传后也会消失。
添加调试信息如下
```typescript
const fileList = ref<any[]>([
// {
//   url: 'https://img12.360buyimg.com//n0/jfs/t1/29118/6/4823/55969/5c35c16bE7c262192/c9fdecec4b419355.jpg'
// }
])
const action: string = 'https://ftf.jd.com/api/uploadImg'
function handleChange({ files }) {
console.log('文件列表改变了: ')
console.log('old: ', fileList.value)
fileList.value = files
console.log('new', fileList.value)
}
```
console输出：
**可以确定是参数解构有问题
查看后面文档发现参数名其实是fileList！**
添加别名解决：
```typescript
function handleChange({ fileList: files }) {
console.log('文件列表改变了: ')
console.log('old: ', fileList.value)
fileList.value = files
console.log('new', fileList.value)
}
```
> docs: ✏️ 修正upload组件文档错误

- src/uni_modules/wot-design-uni/components/common/AbortablePromise.ts
- src/uni_modules/wot-design-uni/components/common/util.ts
- src/uni_modules/wot-design-uni/components/wd-toast/wd-toast.vue
- src/uni_modules/wot-design-uni/components/wd-transition/wd-transition.vue
使用到Transition的组件，再多次连续调用时存在打断动画情况，原transition的实现打断动画后未清除对应的定时器，这些定时器内的逻辑仍会执行，调整后将会在下一次动画打开时，清掉上一个动画的所有定时器、promise。
> fix: 🐛 修复Transition被打断时出现显示异常的问题

- src/uni_modules/wot-design-uni/components/common/util.ts
- src/uni_modules/wot-design-uni/components/wd-grid-item/types.ts
- src/uni_modules/wot-design-uni/components/wd-grid-item/wd-grid-item.vue
- src/uni_modules/wot-design-uni/components/wd-sidebar-item/types.ts
- src/uni_modules/wot-design-uni/components/wd-sidebar-item/wd-sidebar-item.vue
- src/uni_modules/wot-design-uni/components/wd-tabbar-item/types.ts
- src/uni_modules/wot-design-uni/components/wd-tabbar-item/wd-tabbar-item.vue
TabbarItem、SidebarItem和GridItem使用badge用于显示徽标数量，暴露出的badgeProps受到之前提供的isDot属性的默认值影响，部分属性无法生效，做此调整。
> refactor: ♻️  重构tabbar-item、grid-item和sidebar-item透传badge属性的逻辑

- src/uni_modules/wot-design-uni/components/wd-slider/wd-slider.vue
无issue
当使用双向滑块时，通过v-model绑定数组后如`arr = [20, 40]`，则修改`arr[0]`后，组件UI无法更新，而后丢失响应式
不知道怎么贴出最小复现，下面的代码可以复现这个BUG
```vue
<template>
<div>
<wd-button @click="value8[0] = 30">30</wd-button>
<wd-button @click="value8 = [30, 50]">30-50</wd-button>
{{ value8 }}
<wd-slider v-model="value8" :min="10" :max="80" />
</div>
</template>
<script lang="ts" setup>
const value8 = ref<number[]>([20, 40])
</script>
```
点击第二个按钮组件会改变，但是点击第一个按钮（也就是单独修改数组中一项而不是整体改变）就会丢失响应式
> fix: 修复双向滑块响应式丢失

- docs/.vitepress/config.mts
无
随着 `wot-uni-design` 组件数量增加，文档中组件列表太长，位置靠后的组件翻阅体验变差。因此将列表改为允许收起，方便开发者浏览。
> 本次改动不影响现有文档体验，默认全部列表依然展开。
> docs: ✏️  允许文档组件列表折叠收起

- docs/component/swiper.md
- src/pages/swiper/Index.vue
- src/uni_modules/wot-design-uni/components/common/abstracts/variable.scss
- src/uni_modules/wot-design-uni/components/wd-swiper/index.scss
- src/uni_modules/wot-design-uni/components/wd-swiper/types.ts
- src/uni_modules/wot-design-uni/components/wd-swiper/wd-swiper.vue
✅ Closes: #459 
提供支持在h5、微信和钉钉小程序端的视频轮播功能，APP需要NVUE才可以支持。  
提供基于配置的轮播项标题功能
> feat: ✨ Swiper 轮播组件支持展示视频和设置轮播项标题

- docs/component/notice-bar.md
- src/pages/noticeBar/Index.vue
- src/uni_modules/wot-design-uni/components/wd-notice-bar/index.scss
- src/uni_modules/wot-design-uni/components/wd-notice-bar/types.ts
- src/uni_modules/wot-design-uni/components/wd-notice-bar/wd-notice-bar.vue
✅ Closes: #358 #650 
#358 #650 
问题背景：
1. 当前使用transition实现Noticebar的播放动画，动画开始时会使用uni.createSelectorQuery查询节点信息。
2. 当前实现了功能：多行水平轮播。
3. `onActivated`生命周期仅在H5端支持（uni-app文档中标示App也支持，不过实测不支持）。
以上导致没有很好的办法解决此问题，故在`H5`端使用`onActivated`钩子重置动画，并对外提供了`reset`方法，用于重置动画。
> fix: 🐛 修复Notice在Tabbar页面时跳转至其他页面导致播放异常的问题并提供reset方法
